name: Deploy to IONOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to IONOS
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-id: ${{ secrets.IONOS_SERVICE_ID }}
          dist-folder: .next
          project-id: ${{ secrets.IONOS_PROJECT_ID }}
          branch-id: ${{ secrets.IONOS_BRANCH_ID }}

